In [ ]:
!nvidia-smi

Sun Mar  6 09:54:17 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8    29W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import numpy as np
import torch

In [ ]:
#Input_data
input = np.array([[32,55,77],
                  [31,75,57],
                  [52,55,77],
                  [22,100,87],
                  [62,80,77],

                  ], dtype='float32')

In [ ]:
input

array([[ 32.,  55.,  77.],
       [ 31.,  75.,  57.],
       [ 52.,  55.,  77.],
       [ 22., 100.,  87.],
       [ 62.,  80.,  77.]], dtype=float32)

In [ ]:
#target
targets = np.array([[32,66],
                    [52,76],
                    [102,155],
                    [32,26],
                    [99,100],
                    ], dtype='float32')

In [ ]:
targets

array([[ 32.,  66.],
       [ 52.,  76.],
       [102., 155.],
       [ 32.,  26.],
       [ 99., 100.]], dtype=float32)

In [ ]:
inputs = torch.from_numpy(input)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 32.,  55.,  77.],
        [ 31.,  75.,  57.],
        [ 52.,  55.,  77.],
        [ 22., 100.,  87.],
        [ 62.,  80.,  77.]])
tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])


In [ ]:
#Weigts & biases

w = torch.randn(2,3 , requires_grad=True)
b = torch.randn(2 , requires_grad=True)

print(w)
print(b)

tensor([[ 0.0412,  1.2590, -1.2720],
        [ 0.2609,  0.3343,  0.3251]], requires_grad=True)
tensor([-1.4696,  0.8582], requires_grad=True)


In [ ]:
def model(x):
  return x @ w.t() + b

In [ ]:
preds = model(inputs)
print(preds)

tensor([[-28.8501,  52.6259],
        [ 21.7295,  52.5479],
        [-28.0267,  57.8434],
        [ 14.6746,  68.3107],
        [  3.8607,  68.8089]], grad_fn=<AddBackward0>)


In [ ]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])

In [ ]:
# loss

def MSE(t1, t2):
  diff = t1- t2
  return torch.sum(diff * diff) / diff.numel()

In [ ]:
#compute loss

loss = MSE(preds, targets)
print(loss)

tensor(4380.8979, grad_fn=<DivBackward0>)


In [ ]:
#compute gradient

loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[ 0.0412,  1.2590, -1.2720],
        [ 0.2609,  0.3343,  0.3251]], requires_grad=True)
tensor([[-3185.3545, -4422.4385, -5051.1934],
        [-1442.0281, -1220.4625, -1713.6630]])


In [ ]:
with torch.no_grad():
  w -= w.grad * 1e-5   #w(new) = w(old) - learning_rate (dx/dw)
  b -= b.grad * 1e-5

In [ ]:
print(w)

tensor([[ 0.0730,  1.3033, -1.2215],
        [ 0.2753,  0.3465,  0.3423]], requires_grad=True)


In [ ]:
w.grad.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
preds = model(inputs)

In [ ]:
loss = MSE(preds, targets)
print(loss)

tensor(3802.2559, grad_fn=<DivBackward0>)


In [ ]:
#Training
n = 400
for i in range(n):
  preds = model(inputs)
  loss = MSE(preds, targets)
  loss.backward()

  with torch.no_grad():
    w -= w.grad * 1e-5   #w(new) = w(old) - learning_rate (dx/dw)
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

  print(f"Epochs: {i}/{n} ---- Loss: {loss}")



Epochs: 0/400 ---- Loss: 571.2599487304688
Epochs: 1/400 ---- Loss: 569.7034912109375
Epochs: 2/400 ---- Loss: 568.1566162109375
Epochs: 3/400 ---- Loss: 566.6192626953125
Epochs: 4/400 ---- Loss: 565.09130859375
Epochs: 5/400 ---- Loss: 563.572998046875
Epochs: 6/400 ---- Loss: 562.0638427734375
Epochs: 7/400 ---- Loss: 560.5640869140625
Epochs: 8/400 ---- Loss: 559.07373046875
Epochs: 9/400 ---- Loss: 557.5924072265625
Epochs: 10/400 ---- Loss: 556.1199951171875
Epochs: 11/400 ---- Loss: 554.6569213867188
Epochs: 12/400 ---- Loss: 553.2030029296875
Epochs: 13/400 ---- Loss: 551.7578735351562
Epochs: 14/400 ---- Loss: 550.3216552734375
Epochs: 15/400 ---- Loss: 548.8941650390625
Epochs: 16/400 ---- Loss: 547.4757080078125
Epochs: 17/400 ---- Loss: 546.06591796875
Epochs: 18/400 ---- Loss: 544.664794921875
Epochs: 19/400 ---- Loss: 543.2723388671875
Epochs: 20/400 ---- Loss: 541.8885498046875
Epochs: 21/400 ---- Loss: 540.5128784179688
Epochs: 22/400 ---- Loss: 539.1461181640625
Epochs

In [ ]:
preds = model(inputs)
preds

tensor([[ 41.3948,  80.3929],
        [ 55.8980,  52.1113],
        [ 78.9178, 120.3097],
        [ 33.5588,  37.9318],
        [106.3680, 124.0656]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])

# Using Torch built in function

In [ ]:
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')


targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs[0]

tensor([73., 67., 43.])

In [ ]:
#dataloader

from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader

batch_size = 5
train_data = DataLoader(train_ds, batch_size, shuffle=True)

In [ ]:
for xb, yb in train_data:
  print(xb)
  print(yb)
  break

tensor([[ 68.,  97.,  70.],
        [ 73.,  66.,  44.],
        [ 87., 134.,  58.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.]])
tensor([[102., 120.],
        [ 57.,  69.],
        [119., 133.],
        [118., 134.],
        [ 20.,  38.]])


In [ ]:
##nn.linear

#define model

model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5687,  0.5513, -0.0236],
        [-0.1820,  0.3206, -0.0346]], requires_grad=True)
Parameter containing:
tensor([ 0.0323, -0.0153], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5687,  0.5513, -0.0236],
         [-0.1820,  0.3206, -0.0346]], requires_grad=True),
 Parameter containing:
 tensor([ 0.0323, -0.0153], requires_grad=True)]

In [ ]:
preds = model(inputs)
preds

tensor([[ 77.4749,   6.6924],
        [ 98.7950,   9.4226],
        [122.0220,  25.1041],
        [ 80.8778,  -6.0703],
        [ 90.5521,  15.7825],
        [ 77.4923,   6.1899],
        [ 98.2201,   9.0674],
        [122.5671,  24.8875],
        [ 80.8604,  -5.5678],
        [ 89.9598,  15.9299],
        [ 76.9000,   6.3372],
        [ 98.8124,   8.9201],
        [122.5968,  25.4593],
        [ 81.4701,  -6.2176],
        [ 90.5347,  16.2850]], grad_fn=<AddmmBackward0>)

In [ ]:
import torch.nn.functional as F
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(preds, targets)
loss

tensor(4106.7529, grad_fn=<MseLossBackward0>)

In [ ]:
#optimizer

opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [ ]:
# training loop

def fit(num_epochs, model, loss_fn, opt, train_data):

  for epoch in range(num_epochs):
    for xb, yb in train_data:
      pred = model(xb)
      loss = loss_fn(pred, yb)
      loss.backward()
      opt.step()
      opt.zero_grad()

    if (epoch+1) % 10 ==0:
      print("Epoch [{}/{}], Loss: {:.4f}".format(epoch+1, num_epochs, loss))



In [ ]:
fit(100, model, loss_fn, opt, train_data)

Epoch [10/100], Loss: 507.1291
Epoch [20/100], Loss: 177.8215
Epoch [30/100], Loss: 225.3439
Epoch [40/100], Loss: 127.4318
Epoch [50/100], Loss: 186.5381
Epoch [60/100], Loss: 74.9179
Epoch [70/100], Loss: 39.6480
Epoch [80/100], Loss: 31.3548
Epoch [90/100], Loss: 32.8377
Epoch [100/100], Loss: 34.0096


In [ ]:
pred = model(inputs)
pred

tensor([[ 58.4098,  71.2553],
        [ 78.9191,  97.3858],
        [122.4140, 138.2805],
        [ 29.2668,  42.6291],
        [ 91.5565, 110.1911],
        [ 57.2773,  70.1945],
        [ 78.1434,  96.8742],
        [122.4119, 138.5737],
        [ 30.3994,  43.6899],
        [ 91.9134, 110.7402],
        [ 57.6341,  70.7437],
        [ 77.7865,  96.3250],
        [123.1897, 138.7921],
        [ 28.9100,  42.0799],
        [ 92.6891, 111.2519]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
model(torch.tensor([[75,66,44.]]))

tensor([[57.2752, 70.4877]], grad_fn=<AddmmBackward0>)

In [ ]:
pred = pred.to_numpy()

AttributeError: ignored

In [ ]:
pred

In [ ]:
torch.save(model.state_dict(), 'model_weights.pth')

In [ ]:
model = torch.load('model_weights.pth')

In [ ]:
model(torch.tensor([[75,66,44.]]))

TypeError: ignored